name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test -- --json --outputFile=tmp/test_results.json

      - name: Concatenate JSON Payloads
        run: |
          test_results=$(cat tmp/test_results.json)
          payload=$(jq --argjson test "$test_results" '. + {test: $test}' <<EOF
          {
            "repo_name": "${{ github.repository }}",
            "url": "${{ github.event.repository.url }}"
          }
          EOF
          )
          echo "$payload" > tmp/payload.json
        if: always()

      - name: Send JSON to Server
        run: |
          json_payload=$(cat tmp/payload.json)
          signature=$(echo -n "$json_payload" | openssl dgst -sha256 -hmac 'password' | awk '{print $NF}')
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Signature-SHA256: sha256=$signature" \
            -d @tmp/payload.json \
            https://f46d-116-14-38-170.ngrok-free.app/github_payloads
        if: always()
